### ISSUE TITLE
Pyrdp error: No module named 'twisted'

### ISSUE THREAD

**Issue by taosecurity** [GoSecure/pyrdp#108]
Hello, I tried installing Pyrdp on Kali Linux this morning, but encountered this error:

```
(venv) kl@kali:~/pyrdp$ bin/pyrdp-mitm.py 192.168.1.5
Traceback (most recent call last):
  File "bin/pyrdp-mitm.py", line 13, in <module>
    from twisted.internet import asyncioreactor
ModuleNotFoundError: No module named 'twisted'
 
(venv) kl@kali:~/pyrdp$ pip install twisted
Requirement already satisfied: twisted in ./venv/lib/python3.7/site-packages (19.2.0)
Requirement already satisfied: Automat>=0.3.0 in ./venv/lib/python3.7/site-packages (from twisted) (0.7.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./venv/lib/python3.7/site-packages (from twisted) (19.0.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in ./venv/lib/python3.7/site-packages (from twisted) (1.9.0)
Requirement already satisfied: attrs>=17.4.0 in ./venv/lib/python3.7/site-packages (from twisted) (19.1.0)
Requirement already satisfied: incremental>=16.10.1 in ./venv/lib/python3.7/site-packages (from twisted) (17.5.0)
Requirement already satisfied: zope.interface>=4.4.2 in ./venv/lib/python3.7/site-packages (from twisted) (4.6.0)
Requirement already satisfied: constantly>=15.1 in ./venv/lib/python3.7/site-packages (from twisted) (15.1.0)
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from Automat>=0.3.0->twisted) (1.12.0)
Requirement already satisfied: idna>=2.5 in ./venv/lib/python3.7/site-packages (from hyperlink>=17.1.1->twisted) (2.8)
Requirement already satisfied: setuptools in ./venv/lib/python3.7/site-packages (from PyHamcrest>=1.9.0->twisted) (41.0.1)
 
(venv) kl@kali:~/pyrdp$ bin/pyrdp-mitm.py 192.168.1.5
Traceback (most recent call last):
  File "bin/pyrdp-mitm.py", line 13, in <module>
    from twisted.internet import asyncioreactor
ModuleNotFoundError: No module named 'twisted'
```

The following shows all steps I took for installation. Any ideas? Thank you.

https://pastebin.com/LHfk8auF

**Comment by xshill** [comment]
That's very strange :thinking: 

Just as a quick sanity check, can you confirm that `import twisted` also breaks on a python 3 interactive interpreter?

Also, do you have twisted installed outside your virtual environment? (If not, that's fine)

Other things to try:

Does running `pyrdp-mitm.py` (without the `bin/` part) work fine?

Can you show us your python path? (`python3 -c 'import sys; print(sys.path)'`)

Thanks!

**Comment by obilodeau** [comment]
We have not heard back in a while. Closing. Feel free to re-open.
