### ISSUE TITLE
PyRDP crashes when client has a shared folder

### ISSUE THREAD

**Issue by Pourliver** [GoSecure/pyrdp#120]
When trying to share a folder with Remmina, PyRDP crashes. I haven't tested with other client or OSes.
```
[2019-06-17 16:40:51,452] - INFO - John991116 - pyrdp.mitm.connections.security - Client Info: username = '\x00', password = '\x00', domain = '\x00', clientAddress = '127.0.0.1\x00\x00'
[2019-06-17 16:40:55,270] - ERROR - GLOBAL - pyrdp - substring not found
Traceback (most recent call last):
  File "pyrdp/pyrdp/layer/tcp.py", line 90, in dataReceived
    self.recv(data)
  File "pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "pyrdp/pyrdp/layer/segmentation.py", line 79, in recv
    layer.recv(forwarded)
  File "pyrdp/pyrdp/layer/buffered.py", line 55, in recv
    self.pduReceived(pdu)
  File "pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "pyrdp/pyrdp/layer/layer.py", line 143, in recv
    self.pduReceived(pdu)
  File "pyrdp/pyrdp/layer/layer.py", line 110, in pduReceived
    self.observer.onPDUReceived(pdu)
  File "pyrdp/pyrdp/core/observer.py", line 82, in __call__
    self.composite.doCall(self.item, args, kwargs)
  File "pyrdp/pyrdp/core/observer.py", line 56, in doCall
    getattr(observer, item)(*args, **kwargs)
  File "pyrdp/pyrdp/layer/layer.py", line 48, in onPDUReceived
    self.handlers[pdu.header](pdu)
  File "pyrdp/pyrdp/mitm/MCSMITM.py", line 229, in onSendDataRequest
    self.clientChannels[pdu.channelID].recv(pdu.payload)
  File "pyrdp/pyrdp/mcs/channel.py", line 33, in recv
    self.next.recv(data)
  File "pyrdp/pyrdp/layer/rdp/security.py", line 140, in recv
    self.next.recv(data)
  File "pyrdp/pyrdp/layer/rdp/virtual_channel/virtual_channel.py", line 43, in recv
    self.pduReceived(virtualChannelPDU)
  File "pyrdp/pyrdp/layer/layer.py", line 198, in pduReceived
    self.next.recv(pdu.payload)
  File "pyrdp/pyrdp/layer/layer.py", line 142, in recv
    pdu = self.mainParser.parse(data)
  File "pyrdp/pyrdp/parser/rdp/virtual_channel/device_redirection.py", line 110, in parse
    return self.parsers[packetID](stream)
  File "pyrdp/pyrdp/parser/rdp/virtual_channel/device_redirection.py", line 129, in parseDeviceListAnnounce
    deviceList = [self.parseDeviceAnnounce(stream) for _ in range(deviceCount)]
  File "pyrdp/pyrdp/parser/rdp/virtual_channel/device_redirection.py", line 129, in <listcomp>
    deviceList = [self.parseDeviceAnnounce(stream) for _ in range(deviceCount)]
  File "pyrdp/pyrdp/parser/rdp/virtual_channel/device_redirection.py", line 146, in parseDeviceAnnounce
    endIndex = preferredDOSName.index("\x00")
ValueError: substring not found
```

**Comment by Pourliver** [comment]
Fixed in #121
