### ISSUE TITLE
Stacktrace in the player: embedded null character

### ISSUE THREAD

**Issue by obilodeau** [GoSecure/pyrdp#182]
```
$ pyrdp-player.py out/rdp_replay_XXX.pyrdp 
[2020-02-05 16:34:35,815] - INFO - pyrdp.player - Listening for connections on 127.0.0.1:3000
Traceback (most recent call last):
  File "/home/olivier/Documents/gosecure/src/pyrdp/pyrdp/ui/qt.py", line 150, in runOnMainThread
    target()
  File "/home/olivier/Documents/gosecure/src/pyrdp/pyrdp/player/PlayerEventHandler.py", line 60, in <lambda>
    self.viewer.mainThreadHook.emit(lambda: self.onPDUReceived(pdu, True))
  File "/home/olivier/Documents/gosecure/src/pyrdp/pyrdp/player/PlayerEventHandler.py", line 66, in onPDUReceived
    self.handlers[pdu.header](pdu)
  File "/home/olivier/Documents/gosecure/src/pyrdp/pyrdp/player/PlayerEventHandler.py", line 111, in onClipboardData
    self.writeText(f"CLIPBOARD DATA: {clipboardData}")
  File "/home/olivier/Documents/gosecure/src/pyrdp/pyrdp/player/PlayerEventHandler.py", line 52, in writeText
    self.text.insertPlainText(text)
ValueError: embedded null character
```

**Comment by obilodeau** [comment]
According to logs clipboard contained: `https://twisted.readthedocs.io/en/twisted-18.4.0/core/howto/tap.html` so there's clearly a badly handled null byte somewhere or something

**Comment by Res260** [comment]
Is it possible that a Qt version change caused this bug? I dont remember ever seeing it, and I'm pretty sure i copied null bytes.

**Comment by obilodeau** [comment]
```
> /home/olivier/Documents/gosecure/src/pyrdp/pyrdp/player/PlayerEventHandler.py(53)writeText()
     52         import ipdb; ipdb.set_trace()
---> 53         self.text.insertPlainText(text)
     54 

ipdb> text                                                                                                                                                     
'CLIPBOARD DATA: https://twisted.readthedocs.io/en/twisted-18.4.0/core/howto/tap.html\x00'
ipdb> n                                                                                                                                                        
ValueError: embedded null character
```

I think it's more of a Python change but I'm not sure, it could be the client's clipboard that is null-terminated. In any way, it's clear that it is a terminating null byte so we can fix this easily.
