### ISSUE TITLE
Error when connecting to a Windows 10 system with NLA enabled

### ISSUE THREAD

**Issue by guoguo-jiabin** [GoSecure/pyrdp#344]
```
[2021-08-17 15:32:35,486] - INFO - John558674 - pyrdp.mitm.connections.x224 - The server failed the negotiation. Error: The server requires that the client support Enhanced RDP Security (section 5.4) with CredSSP (section 5.4.5.2).
[2021-08-17 15:32:35,494] - INFO - John558674 - pyrdp.mitm.connections.tcp - Server connection closed. Connection to the other side was lost in a non-clean fashion: Connection lost.
Unhandled Error
Traceback (most recent call last):
  File "/Users/lijiabin/anaconda3/lib/python3.7/asyncio/base_events.py", line 528, in run_forever
    self._run_once()
  File "/Users/lijiabin/anaconda3/lib/python3.7/asyncio/base_events.py", line 1764, in _run_once
    handle._run()
  File "/Users/lijiabin/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/lijiabin/PycharmProjects/pyrdp/venv/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 273, in _onTimer
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/Users/lijiabin/PycharmProjects/pyrdp/venv/lib/python3.7/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/Users/lijiabin/PycharmProjects/pyrdp/pyrdp/mitm/RDPMITM.py", line 221, in doClientTls
    cert = self.server.tcp.transport.getPeerCertificate()
  File "/Users/lijiabin/PycharmProjects/pyrdp/venv/lib/python3.7/site-packages/twisted/protocols/tls.py", line 541, in getPeerCertificate
    return self._tlsConnection.get_peer_certificate()
builtins.AttributeError: 'NoneType' object has no attribute 'get_peer_certificate'
```

**Comment by obilodeau** [comment]
The key element in your logs is:

> The server failed the negotiation. Error: The server requires that the client support Enhanced RDP Security (section 5.4) with CredSSP (section 5.4.5.2).

This means that the server requires NLA to be enabled (also known as CredSSP). PyRDP only supports NLA if you extract the certificate from the server. and use `--auth ssp`.

If you are testing out in a lab environment you can either:

a) disable NLA on the RDP server system and try again, [instructions available here](https://www.parallels.com/blogs/ras/disabling-network-level-authentication/#W10WS2016)
b) extract the certificate from the RDP server system and use `--auth ssp`. You can follow [these instructions to extract the certificate](https://github.com/GoSecure/pyrdp/blob/master/docs/cert-extraction.md) and there is an [important update here too](https://github.com/GoSecure/pyrdp/pull/345/files).

Otherwise, you will need another target. One trick is to use a VM w/o NLA and redirect the victim to it. Many enter credentials when fooled that way.

**Comment by obilodeau** [comment]
I am closing this issue but if you feel this is still an issue please let me know in a comment and I will re-open it. Thanks!
