### ISSUE TITLE
Unable to Connect to PyRDP

### ISSUE THREAD

**Issue by s3ldondev** [GoSecure/pyrdp#401]
All nodes are running as VMs on my host: 

PyRDP: Ubuntu 20.04.4 - 172.16.112.130
Victim/User: Win 7 SP1 - 172.16.112.132
Target: Win XP SP3 - 172.16.112.131

All machines have connectivity. I am able to connect an RDP session from the user (Win7) to the target (WinXP). I am able to connect an RDP session from PyRDP (Ubuntu) to the target (WinXP). 

I start PyRDP on the Ubuntu machine: 

`sudo docker run -p 3389:3389 gosecure/pyrdp pyrdp-mitm.py 172.16.112.131`

I then connect RDP from the user (Win7) to PyRDP (Ubuntu). The Win7 machine sees this:

![image](https://user-images.githubusercontent.com/63341146/170110935-0421a003-3c39-4473-9bb1-d723885ad639.png)

and the PyRDP log shows this: 

```
[2022-05-24 18:52:35,533] - INFO - GLOBAL - pyrdp.mitm - Target: 172.16.112.131:3389
[2022-05-24 18:52:35,533] - INFO - GLOBAL - pyrdp.mitm - Output directory: /home/pyrdp/pyrdp_output
[2022-05-24 18:52:35,534] - INFO - GLOBAL - pyrdp - MITM Server listening on 0.0.0.0:3389
[2022-05-24 18:52:39,421] - INFO - Donna244312 - pyrdp.mitm.connections.tcp - New client connected from 172.16.112.132:49172
[2022-05-24 18:52:39,422] - INFO - Donna244312 - pyrdp.mitm.connections.x224 - No cookie for this connection
[2022-05-24 18:52:39,424] - INFO - Donna244312 - pyrdp.mitm.connections.tcp - Server connected
[2022-05-24 18:52:39,444] - INFO - Donna244312 - pyrdp.mitm.connections.tcp - Server connection closed. Connection to the other side was lost in a non-clean fashion: Connection lost.
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/venv/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 273, in _onTimer
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/opt/venv/lib/python3.8/site-packages/twisted/internet/base.py", line 994, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/venv/lib/python3.8/site-packages/pyrdp-1.1.1.dev0-py3.8-linux-x86_64.egg/pyrdp/mitm/RDPMITM.py", line 221, in doClientTls
    cert = self.server.tcp.transport.getPeerCertificate()
  File "/opt/venv/lib/python3.8/site-packages/twisted/protocols/tls.py", line 541, in getPeerCertificate
    return self._tlsConnection.get_peer_certificate()
builtins.AttributeError: 'NoneType' object has no attribute 'get_peer_certificate'
```

**Comment by s3ldondev** [comment]
Resolved:

**Comment by s3ldondev** [comment]
Closed: WinXP SP3 was the issue. Use Windows 7 or later as the target. Unless there is a fix for this?

**Comment by obilodeau** [comment]
Did you disable Network Level Authentication (NLA) on the Win XP SP3?
