### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Sadlava00** [GoSecure/pyrdp#410]
Collecting python-networkmanager
  Using cached python_networkmanager-2.2-py3-none-any.whl (12 kB)
Collecting dbus-python
  Using cached dbus-python-1.3.2.tar.gz (605 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Collecting meson-python>=0.8.1
        Using cached meson_python-0.8.1-py3-none-any.whl (17 kB)
      Collecting meson>=0.60.0
        Using cached meson-0.63.2-py3-none-any.whl (877 kB)
      Collecting ninja
        Using cached ninja-1.10.2.3-py2.py3-none-win_amd64.whl (292 kB)
      Collecting patchelf
        Using cached patchelf-0.15.0.0.tar.gz (150 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools
        Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting pyproject-metadata>=0.5.0
        Using cached pyproject_metadata-0.6.1-py3-none-any.whl (7.4 kB)
      Collecting colorama
        Using cached colorama-0.4.5-py2.py3-none-any.whl (16 kB)
      Collecting tomli>=1.0.0
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting packaging>=19.0
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: patchelf
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Building wheel for patchelf (pyproject.toml) did not run successfully.
        exit code: 1
     
        [9 lines of output]
          File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-rhfaemh9\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 613, in setup
            cmkr = cmaker.CMaker(cmake_executable)
          File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-rhfaemh9\overlay\Lib\site-packages\skbuild\cmaker.py", line 141, in __init__
            self.cmake_version = get_cmake_version(self.cmake_executable)
          File "C:\Users\USERNAME\AppData\Local\Temp\pip-build-env-rhfaemh9\overlay\Lib\site-packages\skbuild\cmaker.py", line 95, in get_cmake_version
            raise SKBuildError(
        Traceback (most recent call last):
     
        Problem with the CMake installation, aborting build. CMake executable is cmake
        [end of output]
     
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
      Failed to build patchelf
      ERROR: Could not build wheels for patchelf, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by eli-schwartz** [comment]
This error happened when installing the build dependency at https://github.com/mayeut/patchelf-pypi

**Comment by Sadlava00** [comment]
> This error happened when installing the build dependency at https://github.com/mayeut/patchelf-pypi

how do I fix it?

**Comment by obilodeau** [comment]
@Sadlava00, can you please indicate which command you ran to get there? I don't see any mention of this project (pyrdp) in your trace. I don't think we have patchelf in our dependency graph.

**Comment by Sadlava00** [comment]
> @Sadlava00, can you please indicate which command you ran to get there? I don't see any mention of this project (pyrdp) in your trace. I don't think we have patchelf in our dependency graph.

`pip install dbus-python`

**Comment by eli-schwartz** [comment]
So it's a recursive build dependency of a totally different project then.

**Comment by Sadlava00** [comment]
> So it's a recursive build dependency of a totally different project then.

its not the same project?

**Comment by eli-schwartz** [comment]
Not entirely sure what you're asking.

Are you asking whether

- pyrdp
- dbus-python

Are the same thing? Because they're spelled quite differently.

**Comment by obilodeau** [comment]
If this can help: pyrdp (this project) depends on `dbus-python` if you want the graphical interface and are on Linux. However, on Windows it shouldn't be pulled and use `win10toast` instead. See https://github.com/GoSecure/pyrdp/blob/master/setup.py#L54

Did you follow the [Windows installation instructions](https://github.com/GoSecure/pyrdp#installing-on-windows)? 

Can you post the full sequence of commands that you ran (and their output) in order to install pyrdp?

**Comment by obilodeau** [comment]
Closing due to inactivity. Feel free to re-open.
