### ISSUE TITLE
Add support for RDP version 10.12

### ISSUE THREAD

**Issue by kobbi-strike** [GoSecure/pyrdp#475]
Error:
```
[2024-05-23 13:19:22,077] - ERROR - wizardly_mirzakhani_5755447 - pyrdp.mitm.connections.tcp - 524305 is not a valid RDPVersion
Traceback (most recent call last):
....
    version = RDPVersion(Uint32LE.unpack(stream))
  File "/usr/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 524305 is not a valid RDPVersion
```

**Comment by kobbi-strike** [comment]
Tried adding ;
    RDP10_12 = 0x80011 to enum/rpd.py

Without any luck.

**Comment by energister** [comment]
@kobbi-strike , why did you close the issue? It's still relevant
