### ISSUE TITLE
Error connection to Windows server 2012

### ISSUE THREAD

**Issue by Romounet** [GoSecure/pyrdp#76]
This could be reproduced to almost all servers running Windows server 2012.
When relaying a connection to a windows server 2012 the connection fails to open with the following stack trace: 

````[2019-02-27 14:38:29,900] - mitm.connections.Paula344551.server                - INFO     - TCP connected from 192.168.160.1:57186
[2019-02-27 14:38:29,902] - mitm.connections.Paula344551.server                - INFO     - No cookie for this connection 
CLIENT_RANDOM 5c76e73564f42e53a944b76f4d4742591f2f41eaf48913a23b68db8f394b6d24 b7e8fa322c0944007d1773a8ffb189cf6cdaf18f77d5aadc221bc8d003546c970be6b95b07c7f00330faabe9facc5184
[2019-02-27 14:38:29,937] - mitm.connections.Paula344551.client                - INFO     - Client Data received with client name DESKTOP-6BGN7C0, resolution 1920x1080
CLIENT_RANDOM 51a82557641ca22407c8f88e22e7af73b9e57b6651c7db2395b31d3e177af4a0 a686495a1e2808478e8a94c00a07e8c23a2528b5087c6c270687ced5ab1072c85319d5dfb0723813933e325f5b3a059c
[2019-02-27 14:38:29,970] - mitm.connections.Paula344551.server                - INFO     - Client address: 192.168.160.1
[2019-02-27 14:38:29,971] - mitm.connections.Paula344551.server                - INFO     - CLIENT INFO RECEIVED.
USER: 
PASSWORD: 
DOMAIN: 
LOCAL IP ADDR: b'1\x009\x002\x00.\x001\x006\x008\x00.\x001\x006\x000\x00.\x001\x00\x00\x00'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/asyncioreactor.py", line 136, in _readOrWrite
    why = method()
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/tcp.py", line 81, in dataReceived
    self.next.recv(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/segmentation.py", line 88, in recv
    layer.recv(forwarded)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/buffered.py", line 52, in recv
    self.pduReceived(pdu, self.hasNext)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/x224.py", line 79, in recv
    self.pduReceived(pdu, pdu.header == X224PDUType.X224_TPDU_DATA)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/mcs.py", line 29, in recv
    self.pduReceived(pdu, self.hasNext)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 123, in pduReceived
    self.observer.onPDUReceived(pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/core/observer.py", line 84, in __call__
    self.composite.doCall(self.item, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/core/observer.py", line 56, in doCall
    getattr(observer, item)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 48, in onPDUReceived
    self.handlers[pdu.header](pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/server.py", line 152, in onSendDataRequest
    user.recvSendDataRequest(pdu.channelID, pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/user.py", line 91, in recvSendDataRequest
    self.channels[channelID].recvSendDataRequest(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/channel.py", line 99, in recvSendDataRequest
    self.pduReceived(pdu, True)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/rdp/security.py", line 151, in recv
    self.next.recv(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/rdp/slowpath.py", line 90, in recv
    pdu = self.mainParser.parse(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/parser/rdp/slowpath.py", line 60, in parse
    header = self.parseShareControlHeader(stream)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/parser/rdp/slowpath.py", line 109, in parseShareControlHeader
    return ShareControlHeader(SlowPathPDUType(pduType & 0xf), (pduType >> 4), source)
  File "/usr/lib/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
builtins.ValueError: 14 is not a valid SlowPathPDUType

[2019-02-27 14:38:29,983] - mitm.connections.Paula344551.server                - INFO     - Connection closed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.

```

**Comment by obilodeau** [comment]
@xshill whenever you have time, I would like to look at this issue with you in a war room so I familiarize myself with this code.

**Comment by Res260** [comment]
^Might be a good idea to wait until the big refactor is merged since the structure will change quite a bit

**Comment by xshill** [comment]
There shouldn't be any more huge changes that haven't been pushed to the branch.

**Comment by Res260** [comment]
Great then open a PR, i'll look at it :)

**Comment by xshill** [comment]
I mean there's still a couple more changes but they're much smaller. I'll open a PR when that's done though.

**Comment by xshill** [comment]
After deleting the `pyrdp.egg-info` folder in the project's directory, the bug stopped happening. It looks like Python was using an old cached version of certain files and this is what was causing the problem.
