### ISSUE TITLE
Error when minimizing rdp window

### ISSUE THREAD

**Issue by Romounet** [GoSecure/pyrdp#77]
The following error can be reproduced when the user minimizes the rdp window:

```[2019-02-27 13:15:36,051] - mitm                                               - INFO     - Using existing private key: /root/.config/pyrdp/private_key.pem
[2019-02-27 13:15:36,052] - mitm                                               - INFO     - Using existing certificate: /root/.config/pyrdp/certificate.pem
[2019-02-27 13:15:36,053] - mitm                                               - INFO     - MITM Server listening on port 3389
[2019-02-27 13:15:41,302] - mitm.connections.Connie125384.server               - INFO     - TCP connected from 192.168.160.151:51728
[2019-02-27 13:15:41,304] - mitm.connections.Connie125384.server               - INFO     - No cookie for this connection 
[2019-02-27 13:15:41,367] - mitm.connections.Connie125384.server               - INFO     - Connection closed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
[2019-02-27 13:15:43,466] - mitm.connections.Christy433553.server              - INFO     - TCP connected from 192.168.160.151:51729
[2019-02-27 13:15:43,467] - mitm.connections.Christy433553.server              - INFO     - No cookie for this connection 
CLIENT_RANDOM 5c76d3cf06a506277972e1c3ad8640f18a88c07b741c98807fbef42de052cf5b 6f556488933f01e6c5ad7671b61b14eaf0368eaee93b4ce5f97ea60b873d2a6aaae68a03daf9cb0441c471a63aa72b47
[2019-02-27 13:15:43,497] - mitm.connections.Christy433553.client              - INFO     - Client Data received with client name DESKTOP-2EASEIK, resolution 1920x1080
CLIENT_RANDOM f6835083c11239a0e3f7996c9033dd37165a5e428808e9cffef03a990e1b3f2c addf2c6602a260d9985db4b94a6d805472e647936722c114f3b4edf8fcf127bb54b9241a2e7cd3e07ce3cae48a20a084
[2019-02-27 13:15:43,555] - mitm.connections.Christy433553.server              - INFO     - Client address: 192.168.160.151
[2019-02-27 13:15:43,558] - mitm.connections.Christy433553.server              - INFO     - CLIENT INFO RECEIVED.
USER: 
PASSWORD: 
DOMAIN: 
LOCAL IP ADDR: b'1\x009\x002\x00.\x001\x006\x008\x00.\x001\x006\x000\x00.\x001\x005\x001\x00\x00\x00'
[2019-02-27 13:15:45,055] - mitm.connections.Christy433553.server.deviceRedirection - INFO     - RDPDR_DTYP_SMARTCARD mapped with ID 1: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/asyncioreactor.py", line 136, in _readOrWrite
    why = method()
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/tcp.py", line 243, in doRead
    return self._dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 330, in dataReceived
    self._flushReceiveBIO()
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/tls.py", line 295, in _flushReceiveBIO
    ProtocolWrapper.dataReceived(self, bytes)
  File "/usr/local/lib/python3.6/dist-packages/Twisted-18.9.0-py3.6-linux-x86_64.egg/twisted/protocols/policies.py", line 120, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/tcp.py", line 81, in dataReceived
    self.next.recv(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/segmentation.py", line 88, in recv
    layer.recv(forwarded)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/buffered.py", line 52, in recv
    self.pduReceived(pdu, self.hasNext)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/x224.py", line 79, in recv
    self.pduReceived(pdu, pdu.header == X224PDUType.X224_TPDU_DATA)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/mcs.py", line 29, in recv
    self.pduReceived(pdu, self.hasNext)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 123, in pduReceived
    self.observer.onPDUReceived(pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/core/observer.py", line 84, in __call__
    self.composite.doCall(self.item, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/core/observer.py", line 56, in doCall
    getattr(observer, item)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 48, in onPDUReceived
    self.handlers[pdu.header](pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/server.py", line 152, in onSendDataRequest
    user.recvSendDataRequest(pdu.channelID, pdu)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/user.py", line 91, in recvSendDataRequest
    self.channels[channelID].recvSendDataRequest(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/mcs/channel.py", line 99, in recvSendDataRequest
    self.pduReceived(pdu, True)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/layer.py", line 126, in pduReceived
    self.next.recv(pdu.payload)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/rdp/security.py", line 151, in recv
    self.next.recv(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/layer/rdp/slowpath.py", line 90, in recv
    pdu = self.mainParser.parse(data)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/parser/rdp/slowpath.py", line 65, in parse
    return self.parsers[header.pduType](stream, header)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/parser/rdp/slowpath.py", line 73, in parseData
    return self.dataParsers[header.subtype](stream, header)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/parser/rdp/slowpath.py", line 468, in parseSuppressOutput
    left = Uint16LE.unpack(stream)
  File "/usr/local/lib/python3.6/dist-packages/pyrdp-1.0.0-py3.6-linux-x86_64.egg/pyrdp/core/packing.py", line 28, in unpack
    raise ValueError(str(e))
builtins.ValueError: unpack requires a buffer of 2 bytes

[2019-02-27 13:15:57,549] - mitm.connections.Christy433553.server              - INFO     - Connection closed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.

```

**Comment by Res260** [comment]
When whom minimises the rdp window?

**Comment by xshill** [comment]
Based on this and #79 it looks like there's an error when parsing Suppress Output PDUs.
